### ISSUE TITLE
Discord invite not working on mobile

### ISSUE THREAD

**Issue by bojanstef** [supertokens/.github#1]
When I manually change the invite link to this format, it works: https://discord.gg/4WXseq7

Otherwise, Discord just opens on mobile and the invite never goes through.

**Comment by rishabhpoddar** [comment]
> Otherwise, Discord just opens on mobile and the invite never goes through.

You are able to see the discord UI though if you visit https://supertokens.com/discord on your web / mobile?

**Comment by bojanstef** [comment]
Whether I go to `https://discord.com/invite/4WXseq7` or `https://supertokens.com/discord` I see the Discord UI but have the same issue of Discord opening but never receiving the invite.

**Comment by bojanstef** [comment]
I was only able to join the server after manually importing the `https://discord.gg/4WXseq7` link through the "Join an existing server" flow in Discord

**Comment by ohansFavour** [comment]
Hi @bojanstef,

Thanks for reporting the issue! Unfortunately, I wasn't able to reproduce the problem on my end. Could you provide some additional details to help troubleshoot further? Specifically, could you let me know:

- The browser you are using

- The operating system on your mobile device (iOS/Android)

- Any additional steps or patterns you've noticed when the issue occurs

This information will help us dig deeper into the issue.

**Comment by rishabhpoddar** [comment]
@ohansFavour , maybe we should just change the link we use to `https://discord.gg/4WXseq7` instead? Cause this works as well, and maybe discord has changed to this format?

**Comment by ohansFavour** [comment]
@rishabhpoddar that makes sense. `.gg` is the format that discord currently uses (I will change the link to this format).

BTW, I found [this post](https://www.reddit.com/r/discordapp/comments/18xjaeb/difference_between_invites_from_discordcominvite/) where someone complained that some users could not also use the `.gg` format.
